#
- name: docker - check bash.d directory exists
  file:
    path: "/etc/bash.d"
    state: "directory"
    mode: 0755
    owner: "root"
    group: "root"

- name: docker - put profile environment
  template:
    src: "docker.rc.j2"
    dest: "/etc/bash.d/docker.rc"
    mode: 0644
    owner: "root"
    group: "root"
