# @see https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: docker - add repository key
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: docker - add repository
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - "deb http://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main"

- name: docker - install
  apt:
    name: "docker-engine"
    state: "present"
