#
- name: docker - install bridge-utils
  apt:
    name: bridge-utils
    state: "present"

- name: docker - remove docker0 interface
  failed_when: False
  shell: "{{ item }}"
  with_items:
    - "/sbin/ip link set dev docker0 down"
    - "/sbin/brctl delbr docker0"
    - "/sbin/iptables -t nat -F POSTROUTING"
