#
- name: docker - setup options
  template:
    src: "docker_options.j2"
    dest: "/etc/default/docker"
    owner: "root"
    group: "root"
    mode: 0644

- include: "xenial/options.yml"
  when: ansible_distribution_release == "xenial"

- name: docker - restart docker (trusty, forced)
  service:
    name: "docker"
    state: "restarted"
  when: ansible_distribution_release == "trusty"

- name: docker - restart docker (xenial, forced)
  systemd:
    name: "docker"
    state: "restarted"
    daemon_reload: "yes"
    enabled: "yes"
  when: ansible_distribution_release == "xenial"
